name: update
on:
  schedule:
    - cron: "45 3 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          ssh-key: ${{ secrets.DEPLOY_KEY }}
      - uses: pnpm/action-setup@v6
      - uses: actions/setup-node@v6
        with:
          cache: pnpm
          node-version: latest
      - run: make deps
      - run: make update-data
      - run: |
          if [[ $(git status --porcelain --untracked-files=no) ]]; then
            git fetch --unshallow --quiet --tags
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git commit -am "automated data update"
            make patch
          else
            echo "Nothing to commit"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
